services:
  php:
    build: .
    image: php:8.4-cli
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - mysql
    environment:
      DATABASE_URL:  ${DATABASE_URL}
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: trendos
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
